CREATE TABLE VEICULO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 NOCACHE)
        PRIMARY KEY,

    MARCA VARCHAR2(50) NOT NULL,
    MODELO VARCHAR2(100) NOT NULL,
    ANO NUMBER NOT NULL,
    COR VARCHAR2(30) NOT NULL,
    PRECO NUMBER(10,2) NOT NULL,
    TIPO VARCHAR2(30) NOT NULL,
    SITUACAO VARCHAR2(20) NOT NULL,
    PLACA VARCHAR2(10) NOT NULL,
    QUILOMETRAGEM NUMBER NOT NULL,

    CONSTRAINT UK_VEICULO_PLACA UNIQUE (PLACA)
);


CREATE TABLE PROPRIETARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1 NOCACHE)
        PRIMARY KEY,

    VEICULOID NUMBER NOT NULL,
    NOMECOMPLETO VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    DATAAQUISICAO DATE NOT NULL,
    DATAVENDA DATE NULL,
    OBSERVACAO VARCHAR2(255),

    CONSTRAINT FK_PROPRIETARIO_VEICULO
        FOREIGN KEY (VEICULOID)
        REFERENCES VEICULO(ID)
);